name: flutter_tools
description: tools for flutter command-line application. useage for ftools.
version: 1.0.0
repository: https://github.com/Mocaris/ftools

environment:
  sdk: '>=2.17.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  args: ^2.5.0
  dart_style: ^2.3.6
  glob: ^2.1.2
  io: ^1.0.4
  yaml: ^3.1.2


dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8


executables:
  ftools: flutter_tools